import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class CheckForBrackets {
	char[] bracketArr = { '[', ']', '(', ')', '{', '}' };

	public static int getCountOfBrackets(String input, char bracketType) {
		long count = input.chars().filter(num -> num == bracketType).count();
		return (int) count;
	}

	public static boolean validateBrackets(String input) {
		if (getCountOfBrackets(input, ']') == getCountOfBrackets(input, '[')) {
			if (getCountOfBrackets(input, '(') == getCountOfBrackets(input, ')')) {
				if (getCountOfBrackets(input, '{') == getCountOfBrackets(input, '}')) {
					return true;
				}
			}
		}
		return false;
	}

	public static void main(String[] args) {
		System.out.println(validateBrackets(inputScanner()));
	}

	public static String inputScanner() {
		System.out.println("Enter text to analyze for all required brackets presence:");
		Scanner sc = new Scanner(System.in);
		return sc.nextLine();
	}

}
