/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.testng.annotations.*;
import static org.testng.Assert.*;

public class AppTest {
    
	@DataProvider(name="inputs")
	public Object[][] inputs(){
		return new Object[][]{
			{"asfsadf[dsfsdf]as]]dfdsf{sdf})fd", '(', 0},
			{"asfsadf[dsfsdf]as]]dfdsf{sdf})fd", ')', 1},
			{"asfsadf[dsfsdf]as]]dfdsf{sdf})fd[", '[', 2},
			{"]asfsadf[dsfsdf]as]]dfdsf{sdf})fd", ']', 4},
			{"asfsadf[dsfsdf]as]]dfdsf{sdf})fd", '}', 1},
			{"asfsadf[dsfsdf]as]]dfd{sf{sdf})fd", '{', 2},
		};
	}
	
	@DataProvider(name="inputValidate")
	public Object[][] inputValidate(){
		return new Object[][]{
			{"asfsadf[dsfsdf]as]]dfdsf{sdf})fd", false},
			{"asfsadf[dsfsdf]asdfdsf{sdf}(0)fd", true},
			{"asfsa[df[dsfsdf]as]dfdsf{sdf})fd{",false },
			{"]asfsadf[dsfsdf]as()dfdsf{sdf})fd", false},
			{"asfsadf[dsfsdf]as()(dfdsf{sdf})fd", true},
			{"asfsa[df[dsfsdf]as]dfd{sf{sdf})fd",false },
		};
	}
	
	@Test(dataProvider="inputs")
	public void checkIfCountBracketsProperly(String input, char bracketType, int count) {
        CheckForBrackets classUnderTest = new CheckForBrackets();
        assertEquals(classUnderTest.getCountOfBrackets(input, bracketType), count);
    }
	
	@Test(dataProvider="inputValidate")
	public void checkIfValidationWorkds(String input, boolean result) {
        CheckForBrackets classUnderTest = new CheckForBrackets();
        assertEquals(classUnderTest.validateBrackets(input), result);
    }
}
